;FLAVOR:Marlin
;TIME:21660
;Filament used: 0m
;Layer height: 0.2
;MINX:100
;MINY:100
;MINZ:100
;MAXX:120
;MAXY:120
;MAXZ:100
; generated by OrcaSlicer 2.0.0 (bed hold job, hand-written)
;machine_type:Adventurer 5M
;right_extruder_temperature:0
;platform_temperature:45
; HEADER_BLOCK_START
; generated by OrcaSlicer
; total layer number: 1
; total filament weight [g] : 0
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
M117 Bed hold 45C for 6h
G90 ; absolute
M83 ; relative E
M104 S0 ; nozzle off
M106 S0 ; part fan off
M140 S45 ; bed 45 C
G28 ; home
G1 Z100 F1200 ; head up out of the way
G1 X110 Y110 F3000 ; park over the centre
M190 S45 ; wait for the bed
;LAYER_CHANGE
;Z:100
;HEIGHT:0.2
;LAYER:0
G1 Z100
G4 S60 ; minute 1 of 360
G4 S60 ; minute 2 of 360
G4 S60 ; minute 3 of 360
G4 S60 ; minute 4 of 360
G4 S60 ; minute 5 of 360
G4 S60 ; minute 6 of 360
G4 S60 ; minute 7 of 360
G4 S60 ; minute 8 of 360
G4 S60 ; minute 9 of 360
G4 S60 ; minute 10 of 360
G4 S60 ; minute 11 of 360
G4 S60 ; minute 12 of 360
G4 S60 ; minute 13 of 360
G4 S60 ; minute 14 of 360
G4 S60 ; minute 15 of 360
G4 S60 ; minute 16 of 360
G4 S60 ; minute 17 of 360
G4 S60 ; minute 18 of 360
G4 S60 ; minute 19 of 360
G4 S60 ; minute 20 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P5 R340
G4 S60 ; minute 21 of 360
G4 S60 ; minute 22 of 360
G4 S60 ; minute 23 of 360
G4 S60 ; minute 24 of 360
G4 S60 ; minute 25 of 360
G4 S60 ; minute 26 of 360
G4 S60 ; minute 27 of 360
G4 S60 ; minute 28 of 360
G4 S60 ; minute 29 of 360
G4 S60 ; minute 30 of 360
G4 S60 ; minute 31 of 360
G4 S60 ; minute 32 of 360
G4 S60 ; minute 33 of 360
G4 S60 ; minute 34 of 360
G4 S60 ; minute 35 of 360
G4 S60 ; minute 36 of 360
G4 S60 ; minute 37 of 360
G4 S60 ; minute 38 of 360
G4 S60 ; minute 39 of 360
G4 S60 ; minute 40 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P11 R320
G4 S60 ; minute 41 of 360
G4 S60 ; minute 42 of 360
G4 S60 ; minute 43 of 360
G4 S60 ; minute 44 of 360
G4 S60 ; minute 45 of 360
G4 S60 ; minute 46 of 360
G4 S60 ; minute 47 of 360
G4 S60 ; minute 48 of 360
G4 S60 ; minute 49 of 360
G4 S60 ; minute 50 of 360
G4 S60 ; minute 51 of 360
G4 S60 ; minute 52 of 360
G4 S60 ; minute 53 of 360
G4 S60 ; minute 54 of 360
G4 S60 ; minute 55 of 360
G4 S60 ; minute 56 of 360
G4 S60 ; minute 57 of 360
G4 S60 ; minute 58 of 360
G4 S60 ; minute 59 of 360
G4 S60 ; minute 60 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P16 R300
G4 S60 ; minute 61 of 360
G4 S60 ; minute 62 of 360
G4 S60 ; minute 63 of 360
G4 S60 ; minute 64 of 360
G4 S60 ; minute 65 of 360
G4 S60 ; minute 66 of 360
G4 S60 ; minute 67 of 360
G4 S60 ; minute 68 of 360
G4 S60 ; minute 69 of 360
G4 S60 ; minute 70 of 360
G4 S60 ; minute 71 of 360
G4 S60 ; minute 72 of 360
G4 S60 ; minute 73 of 360
G4 S60 ; minute 74 of 360
G4 S60 ; minute 75 of 360
G4 S60 ; minute 76 of 360
G4 S60 ; minute 77 of 360
G4 S60 ; minute 78 of 360
G4 S60 ; minute 79 of 360
G4 S60 ; minute 80 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P22 R280
G4 S60 ; minute 81 of 360
G4 S60 ; minute 82 of 360
G4 S60 ; minute 83 of 360
G4 S60 ; minute 84 of 360
G4 S60 ; minute 85 of 360
G4 S60 ; minute 86 of 360
G4 S60 ; minute 87 of 360
G4 S60 ; minute 88 of 360
G4 S60 ; minute 89 of 360
G4 S60 ; minute 90 of 360
G4 S60 ; minute 91 of 360
G4 S60 ; minute 92 of 360
G4 S60 ; minute 93 of 360
G4 S60 ; minute 94 of 360
G4 S60 ; minute 95 of 360
G4 S60 ; minute 96 of 360
G4 S60 ; minute 97 of 360
G4 S60 ; minute 98 of 360
G4 S60 ; minute 99 of 360
G4 S60 ; minute 100 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P27 R260
G4 S60 ; minute 101 of 360
G4 S60 ; minute 102 of 360
G4 S60 ; minute 103 of 360
G4 S60 ; minute 104 of 360
G4 S60 ; minute 105 of 360
G4 S60 ; minute 106 of 360
G4 S60 ; minute 107 of 360
G4 S60 ; minute 108 of 360
G4 S60 ; minute 109 of 360
G4 S60 ; minute 110 of 360
G4 S60 ; minute 111 of 360
G4 S60 ; minute 112 of 360
G4 S60 ; minute 113 of 360
G4 S60 ; minute 114 of 360
G4 S60 ; minute 115 of 360
G4 S60 ; minute 116 of 360
G4 S60 ; minute 117 of 360
G4 S60 ; minute 118 of 360
G4 S60 ; minute 119 of 360
G4 S60 ; minute 120 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P33 R240
G4 S60 ; minute 121 of 360
G4 S60 ; minute 122 of 360
G4 S60 ; minute 123 of 360
G4 S60 ; minute 124 of 360
G4 S60 ; minute 125 of 360
G4 S60 ; minute 126 of 360
G4 S60 ; minute 127 of 360
G4 S60 ; minute 128 of 360
G4 S60 ; minute 129 of 360
G4 S60 ; minute 130 of 360
G4 S60 ; minute 131 of 360
G4 S60 ; minute 132 of 360
G4 S60 ; minute 133 of 360
G4 S60 ; minute 134 of 360
G4 S60 ; minute 135 of 360
G4 S60 ; minute 136 of 360
G4 S60 ; minute 137 of 360
G4 S60 ; minute 138 of 360
G4 S60 ; minute 139 of 360
G4 S60 ; minute 140 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P38 R220
G4 S60 ; minute 141 of 360
G4 S60 ; minute 142 of 360
G4 S60 ; minute 143 of 360
G4 S60 ; minute 144 of 360
G4 S60 ; minute 145 of 360
G4 S60 ; minute 146 of 360
G4 S60 ; minute 147 of 360
G4 S60 ; minute 148 of 360
G4 S60 ; minute 149 of 360
G4 S60 ; minute 150 of 360
G4 S60 ; minute 151 of 360
G4 S60 ; minute 152 of 360
G4 S60 ; minute 153 of 360
G4 S60 ; minute 154 of 360
G4 S60 ; minute 155 of 360
G4 S60 ; minute 156 of 360
G4 S60 ; minute 157 of 360
G4 S60 ; minute 158 of 360
G4 S60 ; minute 159 of 360
G4 S60 ; minute 160 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P44 R200
G4 S60 ; minute 161 of 360
G4 S60 ; minute 162 of 360
G4 S60 ; minute 163 of 360
G4 S60 ; minute 164 of 360
G4 S60 ; minute 165 of 360
G4 S60 ; minute 166 of 360
G4 S60 ; minute 167 of 360
G4 S60 ; minute 168 of 360
G4 S60 ; minute 169 of 360
G4 S60 ; minute 170 of 360
G4 S60 ; minute 171 of 360
G4 S60 ; minute 172 of 360
G4 S60 ; minute 173 of 360
G4 S60 ; minute 174 of 360
G4 S60 ; minute 175 of 360
G4 S60 ; minute 176 of 360
G4 S60 ; minute 177 of 360
G4 S60 ; minute 178 of 360
G4 S60 ; minute 179 of 360
G4 S60 ; minute 180 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P50 R180
G4 S60 ; minute 181 of 360
G4 S60 ; minute 182 of 360
G4 S60 ; minute 183 of 360
G4 S60 ; minute 184 of 360
G4 S60 ; minute 185 of 360
G4 S60 ; minute 186 of 360
G4 S60 ; minute 187 of 360
G4 S60 ; minute 188 of 360
G4 S60 ; minute 189 of 360
G4 S60 ; minute 190 of 360
G4 S60 ; minute 191 of 360
G4 S60 ; minute 192 of 360
G4 S60 ; minute 193 of 360
G4 S60 ; minute 194 of 360
G4 S60 ; minute 195 of 360
G4 S60 ; minute 196 of 360
G4 S60 ; minute 197 of 360
G4 S60 ; minute 198 of 360
G4 S60 ; minute 199 of 360
G4 S60 ; minute 200 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P55 R160
G4 S60 ; minute 201 of 360
G4 S60 ; minute 202 of 360
G4 S60 ; minute 203 of 360
G4 S60 ; minute 204 of 360
G4 S60 ; minute 205 of 360
G4 S60 ; minute 206 of 360
G4 S60 ; minute 207 of 360
G4 S60 ; minute 208 of 360
G4 S60 ; minute 209 of 360
G4 S60 ; minute 210 of 360
G4 S60 ; minute 211 of 360
G4 S60 ; minute 212 of 360
G4 S60 ; minute 213 of 360
G4 S60 ; minute 214 of 360
G4 S60 ; minute 215 of 360
G4 S60 ; minute 216 of 360
G4 S60 ; minute 217 of 360
G4 S60 ; minute 218 of 360
G4 S60 ; minute 219 of 360
G4 S60 ; minute 220 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P61 R140
G4 S60 ; minute 221 of 360
G4 S60 ; minute 222 of 360
G4 S60 ; minute 223 of 360
G4 S60 ; minute 224 of 360
G4 S60 ; minute 225 of 360
G4 S60 ; minute 226 of 360
G4 S60 ; minute 227 of 360
G4 S60 ; minute 228 of 360
G4 S60 ; minute 229 of 360
G4 S60 ; minute 230 of 360
G4 S60 ; minute 231 of 360
G4 S60 ; minute 232 of 360
G4 S60 ; minute 233 of 360
G4 S60 ; minute 234 of 360
G4 S60 ; minute 235 of 360
G4 S60 ; minute 236 of 360
G4 S60 ; minute 237 of 360
G4 S60 ; minute 238 of 360
G4 S60 ; minute 239 of 360
G4 S60 ; minute 240 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P66 R120
G4 S60 ; minute 241 of 360
G4 S60 ; minute 242 of 360
G4 S60 ; minute 243 of 360
G4 S60 ; minute 244 of 360
G4 S60 ; minute 245 of 360
G4 S60 ; minute 246 of 360
G4 S60 ; minute 247 of 360
G4 S60 ; minute 248 of 360
G4 S60 ; minute 249 of 360
G4 S60 ; minute 250 of 360
G4 S60 ; minute 251 of 360
G4 S60 ; minute 252 of 360
G4 S60 ; minute 253 of 360
G4 S60 ; minute 254 of 360
G4 S60 ; minute 255 of 360
G4 S60 ; minute 256 of 360
G4 S60 ; minute 257 of 360
G4 S60 ; minute 258 of 360
G4 S60 ; minute 259 of 360
G4 S60 ; minute 260 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P72 R100
G4 S60 ; minute 261 of 360
G4 S60 ; minute 262 of 360
G4 S60 ; minute 263 of 360
G4 S60 ; minute 264 of 360
G4 S60 ; minute 265 of 360
G4 S60 ; minute 266 of 360
G4 S60 ; minute 267 of 360
G4 S60 ; minute 268 of 360
G4 S60 ; minute 269 of 360
G4 S60 ; minute 270 of 360
G4 S60 ; minute 271 of 360
G4 S60 ; minute 272 of 360
G4 S60 ; minute 273 of 360
G4 S60 ; minute 274 of 360
G4 S60 ; minute 275 of 360
G4 S60 ; minute 276 of 360
G4 S60 ; minute 277 of 360
G4 S60 ; minute 278 of 360
G4 S60 ; minute 279 of 360
G4 S60 ; minute 280 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P77 R80
G4 S60 ; minute 281 of 360
G4 S60 ; minute 282 of 360
G4 S60 ; minute 283 of 360
G4 S60 ; minute 284 of 360
G4 S60 ; minute 285 of 360
G4 S60 ; minute 286 of 360
G4 S60 ; minute 287 of 360
G4 S60 ; minute 288 of 360
G4 S60 ; minute 289 of 360
G4 S60 ; minute 290 of 360
G4 S60 ; minute 291 of 360
G4 S60 ; minute 292 of 360
G4 S60 ; minute 293 of 360
G4 S60 ; minute 294 of 360
G4 S60 ; minute 295 of 360
G4 S60 ; minute 296 of 360
G4 S60 ; minute 297 of 360
G4 S60 ; minute 298 of 360
G4 S60 ; minute 299 of 360
G4 S60 ; minute 300 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P83 R60
G4 S60 ; minute 301 of 360
G4 S60 ; minute 302 of 360
G4 S60 ; minute 303 of 360
G4 S60 ; minute 304 of 360
G4 S60 ; minute 305 of 360
G4 S60 ; minute 306 of 360
G4 S60 ; minute 307 of 360
G4 S60 ; minute 308 of 360
G4 S60 ; minute 309 of 360
G4 S60 ; minute 310 of 360
G4 S60 ; minute 311 of 360
G4 S60 ; minute 312 of 360
G4 S60 ; minute 313 of 360
G4 S60 ; minute 314 of 360
G4 S60 ; minute 315 of 360
G4 S60 ; minute 316 of 360
G4 S60 ; minute 317 of 360
G4 S60 ; minute 318 of 360
G4 S60 ; minute 319 of 360
G4 S60 ; minute 320 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P88 R40
G4 S60 ; minute 321 of 360
G4 S60 ; minute 322 of 360
G4 S60 ; minute 323 of 360
G4 S60 ; minute 324 of 360
G4 S60 ; minute 325 of 360
G4 S60 ; minute 326 of 360
G4 S60 ; minute 327 of 360
G4 S60 ; minute 328 of 360
G4 S60 ; minute 329 of 360
G4 S60 ; minute 330 of 360
G4 S60 ; minute 331 of 360
G4 S60 ; minute 332 of 360
G4 S60 ; minute 333 of 360
G4 S60 ; minute 334 of 360
G4 S60 ; minute 335 of 360
G4 S60 ; minute 336 of 360
G4 S60 ; minute 337 of 360
G4 S60 ; minute 338 of 360
G4 S60 ; minute 339 of 360
G4 S60 ; minute 340 of 360
M140 S45 ; re-assert bed target
G1 X110 Y110 F600 ; keep-alive nudge
M73 P94 R20
G4 S60 ; minute 341 of 360
G4 S60 ; minute 342 of 360
G4 S60 ; minute 343 of 360
G4 S60 ; minute 344 of 360
G4 S60 ; minute 345 of 360
G4 S60 ; minute 346 of 360
G4 S60 ; minute 347 of 360
G4 S60 ; minute 348 of 360
G4 S60 ; minute 349 of 360
G4 S60 ; minute 350 of 360
G4 S60 ; minute 351 of 360
G4 S60 ; minute 352 of 360
G4 S60 ; minute 353 of 360
G4 S60 ; minute 354 of 360
G4 S60 ; minute 355 of 360
G4 S60 ; minute 356 of 360
G4 S60 ; minute 357 of 360
G4 S60 ; minute 358 of 360
G4 S60 ; minute 359 of 360
G4 S60 ; minute 360 of 360
M140 S45 ; re-assert bed target
G1 X111 Y110 F600 ; keep-alive nudge
M73 P100 R0
M140 S0 ; bed off
M104 S0
M107
G1 Z110 F600
M84 ; motors off
M117 Bed hold finished
; EXECUTABLE_BLOCK_END
